import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import "./globals.css";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LoginComponent from "@/components/LoginComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Chat Application",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (<LoginComponent />) : (<div className="flex">
            {/**Side bar */}
            <div className="bg-[#000000] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
              <SideBar />
            </div>
            
            {/**Client Provider - Notification */}

            <div className="bg-[#343541] flex-1">{children}</div>
          </div>)}
        </SessionProvider>
      </body>
    </html>
  );
}
